# Generated by Django 5.0.1 on 2024-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('team_no', models.IntegerField(unique=True)),
                ('round_no', models.IntegerField(default=0)),
                ('ppt_link', models.URLField(blank=True)),
                ('mode', models.CharField(default='online', max_length=50)),
                ('team_name', models.CharField(max_length=255)),
            ],
        ),
    ]
