# Generated by Django 5.0.1 on 2024-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_judge_judge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='feedback1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='feedback_overall',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='github_link2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='github_link3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ieee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='ieee_member',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='team',
            name='member2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ppt3_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
