# Generated by Django 5.0.1 on 2024-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_team_github_link1'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
