# Generated by Django 5.0.1 on 2024-04-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_team_member_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.IntegerField(unique=True)),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('github_link1', models.URLField(blank=True)),
                ('ieee_member', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('ieee_id', models.CharField(blank=True, max_length=50)),
                ('ppt_link', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='github_link1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ieee_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ieee_member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ppt_link',
        ),
    ]
