# Generated by Django 5.0.1 on 2024-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_round1_remove_team_github_link1_remove_team_ieee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Round1',
        ),
        migrations.AddField(
            model_name='team',
            name='github_link1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ieee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='ieee_member',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='team',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='ppt_link',
            field=models.URLField(blank=True),
        ),
    ]
