# Generated by Django 5.0.1 on 2024-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_round1_remove_team_github_link1_remove_team_ieee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round1',
            name='mode',
            field=models.CharField(default='online', max_length=50),
        ),
    ]
