# Generated by Django 5.0.1 on 2024-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_round1_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.IntegerField(unique=True)),
                ('team_name', models.CharField(max_length=255)),
                ('mode', models.CharField(default='online', max_length=50)),
                ('youtube_link', models.URLField(blank=True)),
                ('github_link2', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.IntegerField(unique=True)),
                ('team_name', models.CharField(max_length=255)),
                ('mode', models.CharField(default='online', max_length=50)),
                ('github_link3', models.URLField(blank=True)),
                ('ppt3_link', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='github_link2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='github_link3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ppt3_link',
        ),
        migrations.RemoveField(
            model_name='team',
            name='youtube_link',
        ),
    ]
