# Generated by Django 5.0.1 on 2024-04-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_round2_round3_remove_team_github_link2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round1',
            name='mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='round2',
            name='mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='round3',
            name='mode',
            field=models.CharField(max_length=50),
        ),
    ]
