# Generated by Django 5.0.1 on 2024-04-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_round1_mode_alter_round2_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2',
            name='github_link2',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round2',
            name='youtube_link',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round3',
            name='github_link3',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='round3',
            name='ppt3_link',
            field=models.URLField(max_length=255),
        ),
    ]
