# Generated by Django 5.0.1 on 2024-04-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_round2_github_link2_alter_round2_youtube_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round1',
            name='ieee_id',
        ),
        migrations.RemoveField(
            model_name='round1',
            name='ieee_member',
        ),
    ]
