# Generated by Django 5.0.1 on 2024-04-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_round1_ieee_id_remove_round1_ieee_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='round2',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='round3',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
