# Generated by Django 5.0.1 on 2024-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_round2_member_name_round3_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='feedback1',
        ),
        migrations.AddField(
            model_name='round1',
            name='youtube_link1',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='round2',
            name='ppt_link2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='round3',
            name='youtube_link3',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
