# Generated by Django 5.0.1 on 2024-04-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_team_feedback1_round1_youtube_link1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round1',
            name='ieee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='round1',
            name='ieee_member',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
