# Generated by Django 5.0.1 on 2024-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_round1_ieee_id_round1_ieee_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round1',
            name='ieee_member',
            field=models.CharField(max_length=3),
        ),
    ]
