# Generated by Django 5.0.1 on 2024-04-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_round1_ieee_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round1',
            name='ieee_id',
        ),
        migrations.RemoveField(
            model_name='round1',
            name='ieee_member',
        ),
    ]
